#pragma once
#include "core/Math.h"
#include "assembly/ObjectAssembly.h"
#include <string>
#include <vector>
#include <memory>
#include <functional>

// ─────────────────────────────────────────────────────────────────────────────
//  SceneBlueprint.h  —  High-level description of a complete 3D scene that
//  can be generated by the AI system or constructed procedurally.
//
//  The blueprint is pure data (no GL, no scene pointers) so it can be
//  serialised, transmitted, or generated offline.
// ─────────────────────────────────────────────────────────────────────────────

struct ObjectBlueprint3D {
    std::string              name;
    std::string              typeName;      // "car", "crate", "tree", "building", …
    Vec3                     position;
    Vec3                     rotationDeg;
    Vec3                     scale          = Vec3(1,1,1);
    Vec4                     color          = Vec4(1,1,1,1);

    // Physics role: "dynamic", "static", "kinematic", "none"
    std::string              physicsRole    = "none";

    // Sub-parts (for compound objects)
    std::vector<ObjectBlueprint3D> children;

    // Optional controller type: "car", "character", "projectile", ""
    std::string              controller;

    // Optional AI script snippet tag
    std::string              scriptTag;
};

struct LightBlueprint3D {
    enum class LightType { Directional, Point, Spot };
    LightType   type          = LightType::Point;
    Vec3        position;
    Vec3        directionDeg;  // Euler pitch/yaw for directional / spot
    Vec4        color         = Vec4(1,1,1,1);
    float       intensity     = 1.0f;
    float       range         = 10.0f;
    float       spotAngleDeg  = 30.0f;
    bool        castShadows   = true;
};

struct CameraBlueprint3D {
    Vec3  position      = Vec3(0, 5, -10);
    Vec3  targetPos     = Vec3(0, 0, 0);
    float fovDeg        = 60.0f;
    float nearPlane     = 0.1f;
    float farPlane      = 1000.0f;
    bool  followTarget  = false;
    std::string followObjectName;
    Vec3  followOffset  = Vec3(0, 4, -8);
};

struct SceneBlueprint3D {
    std::string                  sceneName;
    Vec4                         skyColor    = Vec4(0.4f, 0.7f, 1.0f, 1.0f);
    Vec3                         gravity     = Vec3(0, -9.81f, 0);
    float                        ambientIntensity = 0.2f;

    std::vector<ObjectBlueprint3D> objects;
    std::vector<LightBlueprint3D>  lights;
    CameraBlueprint3D              camera;

    // Serialise to plain text (round-trippable)
    std::string  Serialize()   const;
    static SceneBlueprint3D Deserialize(const std::string& data);

    // Template scenes
    static SceneBlueprint3D EmptyCity();
    static SceneBlueprint3D CarParkScene();
    static SceneBlueprint3D RacingTrack();
};

// ─────────────────────────────────────────────────────────────────────────────
//  SceneGenerator3D  —  Builds a scene from a blueprint or a text prompt.
// ─────────────────────────────────────────────────────────────────────────────

class Scene;
class PhysicsWorld;

class SceneGenerator3D {
public:
    SceneGenerator3D(Scene* scene, PhysicsWorld* physics = nullptr)
        : m_Scene(scene), m_Physics(physics) {}

    // Spawn all objects from a blueprint into the current scene
    void Spawn(const SceneBlueprint3D& blueprint);

    // Spawn a single object blueprint (recursive for children)
    class GameObject* SpawnObject(const ObjectBlueprint3D& bp,
                                   class GameObject*         parent = nullptr);

    // Optional progress callback: (objectsSpawned, total)
    void SetProgressCallback(std::function<void(int,int)> cb) { m_ProgressCb = cb; }

private:
    Scene*        m_Scene  = nullptr;
    PhysicsWorld* m_Physics = nullptr;
    std::function<void(int,int)> m_ProgressCb;
};
